config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'comics/index'

  resources :comics, only: [:index, :show, :create, :destroy, :update]
  resources :favorites, only: [:index, :create, :destroy]

  namespace :admin do
    resources :comics
  end

  root 'comics#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  has_many :favorites
  has_many :users, through: :favorites
end

app/models/comic_scraper.rb
require 'open-uri'

class ComicScraper

  ###############################
  #######   Buttersafe   ########
  ###############################

  def self.buttersafe_info
    explosm = {"name" => "Buttersafe",
      "image" => buttersafe_image,
      "archive" => "http://buttersafe.com/archive/"}
    explosm
  end

  def self.buttersafe_image
    doc = Nokogiri::HTML(open('http://buttersafe.com/'))
    src = doc.css("div#comic img").attr('src')
    "#{src}"
  end

  ###############################
  ####   Dinosaur Comcis   ######
  ###############################

  def self.dino_info
    explosm = {"name" => "Dinosaur Comics",
      "image" => dino_image,
      "archive" => "http://www.qwantz.com/archive.php"}
    explosm
  end

  def self.dino_image
    doc = Nokogiri::HTML(open('http://www.qwantz.com/index.php'))
    src = doc.css("center img").attr('src')
    "#{src}"
  end

  ###############################
  ########   explosm   ##########
  ###############################

  def self.explosm_info
    explosm = {"name" => "Explosm",
      "image" => explosm_image,
      "archive" => "http://explosm.net/comics/archive"}
    explosm
  end

  def self.explosm_image
    doc = Nokogiri::HTML(open('http://explosm.net/comics/latest'))
    src = doc.css("div#comic-container img").attr('src')
    "#{src}"
  end

  ###############################
  ##########   SMBC   ###########
  ###############################

  def self.smbc_info
    explosm = {"name" => "Saturday Morning Breakfast Cereal",
      "image" => smbc_image,
      "archive" => "http://www.smbc-comics.com/archives.php"}
    explosm
  end

  def self.smbc_image
    doc = Nokogiri::HTML(open('http://www.smbc-comics.com/'))
    src = doc.css("div#comicimage img").attr('src')
    "#{src}"
  end

  ###############################
  ##########   XKCD   ###########
  ###############################

  def self.xkcd_info
    xkcd = {"name" => "XKCD",
      "image" => xkcd_image,
      "archive" => "http://xkcd.com/archive/"}
    xkcd
  end

  def self.xkcd_image
    doc = Nokogiri::HTML(open('http://xkcd.com/'))
    src = doc.css("div#comic img").attr('src')
    "#{src}"
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :comic

  validates_uniqueness_of :user_id,  scope: [:comic_id ]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :comics, through: :favorites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < ApplicationController
  before_filter :check_if_admin
  def index
    @comics = Comic.all
  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comic_params)

    if @comic.save
      redirect_to admin_comics_path
      flash[:notice] = "You have successfully entered a new car listing"
    else
      render :new
    end
  end

  def edit
    @comic = Comic.find(params[:id])
  end

  def destroy
    @comic = Comic.find(params[:id])
    if @comic.destroy
      flash[:notice] = "Comic successfully deleted"
      redirect_to admin_comics_path
    else
      flash[:alert] = "Failed to delete comic."
      redirect_to admin_comics_path
    end
  end

  private

  def comic_params
    params.require(:comic).permit(:name, :scraper_url, :scraper_div, :scraper_src, :archive_url)
  end

  protected

  def check_if_admin
    if current_user.admin?
      else
          flash[:notice] = "You are not authorized to access this page."
        redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comics_controller.rb
require 'open-uri'
class ComicsController < ApplicationController
  def index
    if signed_in?
      @comic = current_user.comics
    end
  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comic_params)
    if @comic.save
      redirect_to admin_comics_path
      flash[:notice] = "You have successfully entered a new car listing"
    else
      render :new
    end
  end

  def update
    @comic = Comic.find(params[:id])
    if @comic.update(comic_params)
      redirect_to admin_comics_path
      flash[:notice] = "Your comic has been successfully updated."
    else
      render :edit
      flash[:alert] = "Please fill out the forms correctly."
    end
  end

  private

  def comic_params
    params.require(:comic).permit(:name, :scraper_url, :scraper_div, :scraper_src, :archive_url)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    if signed_in?
      @comic = Comic.all
    else
      flash[:notice] = "You must be logged in to access this page."
      redirect_to root_path
    end
  end

  def create
    @favorite = Favorite.new(user: current_user, comic_id: params[:format])
    if @favorite.save
      redirect_to favorites_path, notice: 'Comic has been favorited!'
    else
      redirect_to favorites_path, alert: 'You have already favorited this comic!'
    end
  end

  def destroy
    @favorite = Favorite.where(user: current_user, comic_id: params[:id])
    if Favorite.where(user: current_user, comic_id: params[:id]).empty?
      redirect_to favorites_path, alert: 'You aren\'t subscribed to this comic!'
    else
      @favorite.destroy(@favorite)
      redirect_to favorites_path, notice: "Your comic has been successfully deleted."
    end
  end

  private

  # def favorite_params
  #   params.require(:favorite).permit(:user, :format)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/comics/_edit_comic_form.html.erb
<%= form_for @comic do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :scraper_url %>
    <%= f.text_field :scraper_url %>
  </div>

  <div>
    <%= f.label :scraper_div %>
    <%= f.text_field :scraper_div %>
  </div>

  <div>
    <%= f.label :scraper_src %>
    <%= f.text_field :scraper_src %>
  </div>

  <div>
    <%= f.label :archive_url %>
    <%= f.text_field :archive_url %>
  </div>

  <p>
    <%= f.submit "Submit Admin Comic" %>
  </p>

<% end %>

app/views/admin/comics/_new_comic_form.html.erb
<%= form_for @comic do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :scraper_url %>
    <%= f.text_field :scraper_url %>
  </div>

  <div>
    <%= f.label :scraper_div %>
    <%= f.text_field :scraper_div %>
  </div>

  <div>
    <%= f.label :scraper_src %>
    <%= f.text_field :scraper_src %>
  </div>

  <div>
    <%= f.label :archive_url %>
    <%= f.text_field :archive_url %>
  </div>

  <p>
    <%= f.submit "Submit Admin Comic" %>
  </p>

<% end %>

app/views/admin/comics/edit.html.erb
<% if @comic.errors.any? %>
  <div><% @comic.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

<div class="row">
  <div class="small-6 large-centered columns">
    <div class="panel2">
      <h2>Comic Form</h2>

      <%= render "edit_comic_form" %>
    </div>
  </div>
</div>

app/views/admin/comics/index.html.erb
<div class="row">
  <div class="small-10 large-centered columns">
    <h3> Admin Section </h3>
    <p><%= link_to 'Add new comic', new_admin_comic_path %></p>
    <TABLE>
      <TR>
        <TD><strong>id</TD>
        <TD><strong>comic name</TD>
        <TD><strong>scraper_url</TD>
        <TD><strong>scraper_div</TD>
        <TD><strong>scraper_src</TD>
        <TD><strong>archive_url</TD>
      </TR>
      <% @comics.each do |info| %>
        <TR>
          <TD><%= info.id %></TD>
          <TD><%= info.name %></TD>
          <TD><%= info.scraper_url %></TD>
          <TD><%= info.scraper_div %></TD>
          <TD><%= info.scraper_src %></TD>
          <TD><%= info.archive_url %></TD>
          <TD><%= link_to 'Edit', edit_admin_comic_path(info) %></TD>
          <TD><%= link_to 'Delete', admin_comic_path(info), method: :delete, data: { confirm: "Are you sure?"} %></TD>
        </TR>
      <% end %>
    </TABLE>
  </div>
</div>

app/views/admin/comics/new.html.erb
<div class="row">
  <div class="small-6 large-centered columns">
    <div class="panel2">
      <h2>Comic Form</h2>

      <%= render "new_comic_form" %>
    </div>
  </div>
</div>

app/views/comics/index.html.erb
<% if signed_in? %>
  <% if @comic.empty? %>
    <div class="row">
      <div class="small-10 large-centered columns">
        <div class="panel">
          <p>You haven't subscribed to any comics! Click on settings and subscribe to some!</p>
        </div>
      </div>
    </div>
  <% else %>
    <% @comic.each do |list| %>
      <div class="row">
        <div class="small-10 large-centered columns">
          <div class="panel">
            <h3><strong><%= list.name %></strong></h3>
            <p></p>
             <% doc = Nokogiri::HTML(open(list.scraper_url)) %>
             <% src = doc.css(list.scraper_div).attr(list.scraper_src) %>
             <img src="<%= "#{src}" %>" />
            <p></p>
            <a href=<%= list.archive_url %>><%=list.name %> archive</a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class="row">
    <div class="small-4 large-centered columns">
      <div class="panel">
        <p>Please sign-up/sign-in</p>
      </div>
    </div>
  </div>
<% end %>

app/views/favorites/index.html.erb
<div class="row">
  <div class="small-6 large-centered columns">
      <TABLE>
        <TR>
          <TD><strong>Comic</TD>
          <TD><strong>Add</TD>
          <TD><strong>Remove</TD>
          <TD><strong>Homepage</TD>
        </TR>
          <% @comic.each do |list| %>
          <TR>
            <TD><strong><%= list.name %></strong></TD>
            <TD><%= link_to "Add", favorites_path(list), method: :post %></TD>
            <TD><%= link_to "Remove", favorite_path(list), method: :delete %></TD>
            <TD><a href=<%= list.scraper_url %>><%=list.name %> Home</a></TD>
          </TR>
        <% end %>
      </TABLE>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kapow</title>
  <link rel="stylesheet" href="/css/foundation.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="contain-to-grid sticky">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to image_tag("/img/kapow.png", :width => 150), root_path, {:class => 'name'} %></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <% if user_signed_in? %>
            <li class="active"><a href="#">Logged in as <%= current_user.email %></a></li>
            <% if current_user.admin? %>
              <li><%= link_to "Admin", admin_comics_path  %></li>
            <% end %>
            <li><%= link_to 'Settings', favorites_path %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
          <% end %>
        </ul>
        </ul>
      </section>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </nav>
  </div>

  <div class="row">
    <div class="large-6 columns"><p></p></div>
  </div>

    <% if notice %>
      <p class="alert-box alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert-box alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>This is a project by Jamie Francese</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Info</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">About</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

</body>
</html>
<!DOCTYPE html>
<html>

app/views/settings/index.html.erb
<div class="row">
  <div class="small-10 large-centered columns">
    <% @comic.each do |list| %>
      <br>
      
      <strong><%= list.name %></strong>
    <% end %>
  </div>
</div>